{% set name = "httpstan" %}
{% set version = "4.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/stan-dev/httpstan/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6b15a07557715e79e6fd66993930003b270f8b8b0c9e65f84978afe5e6bb3047

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [py<37]


requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - poetry  >=1.1.4
    - pybind11  >=2.6.2
    - python
  run:
    - aiohttp  >=3.7
    - appdirs  >=1.4
    - lz4  >=3.1
    - marshmallow  >=3.10
    - numpy  >=1.16
    - python
    - setuptools  >=41.0
    - webargs  >=7.0

test:
  imports:
    - httpstan
    - httpstan.services

about:
  home: https://pypi.org/project/httpstan/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: HTTP-based REST interface to Stan, a package for Bayesian inference.
  doc_url: https://httpstan.readthedocs.io/
  dev_url: https://github.com/stan-dev/httpstan

extra:
  recipe-maintainers:
    - mxr-conda
    - achangeo
    - oblute
